# Generated by Django 4.2 on 2023-04-28 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("garagem", "0005_veiculo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acessorio",
            options={"verbose_name": "Acessório"},
        ),
        migrations.AlterModelOptions(
            name="cor",
            options={"verbose_name_plural": "Cores"},
        ),
        migrations.AlterModelOptions(
            name="veiculo",
            options={"verbose_name": "Veículo"},
        ),
        migrations.RemoveField(
            model_name="veiculo",
            name="modelo",
        ),
        migrations.CreateModel(
            name="Modelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=70)),
                (
                    "marca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="modelo",
                        to="garagem.marca",
                    ),
                ),
            ],
        ),
    ]
