# Generated by Django 4.2 on 2023-05-02 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("garagem", "0006_alter_acessorio_options_alter_cor_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="veiculo",
            name="modelo",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="veículo",
                to="garagem.modelo",
            ),
            preserve_default=False,
        ),
    ]
