# Generated by Django 4.2.5 on 2023-09-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0009_veiculo_description_veiculo_image_veiculo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
